SELECT * WHERE {
  ?item p:P31/ps:P31/wdt:P279* wd:Q473972.
	{
		SELECT (MAX(?naturbase) AS ?naturbase) ?item WHERE {
            ?item wdt:P1732 ?naturbase.
       }
		GROUP BY ?item
		ORDER BY DESC(?naturbase)
	}
  OPTIONAL { ?item wdt:P2044 ?elevation. }
  OPTIONAL { ?item wdt:P856 ?url. }
  OPTIONAL { ?item wdt:P18 ?foto. }
  OPTIONAL { ?item wdt:P625 ?coords. }
  OPTIONAL { ?item wdt:P571 ?inception. }
  OPTIONAL { ?item wdt:P576 ?dissolved. }
  OPTIONAL { ?item wdt:P1732 ?naturbase. }
  OPTIONAL {
    ?article schema:about ?item;
      schema:isPartOf <https://no.wikipedia.org/>.
  }
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "nb".
    ?item rdfs:label ?itemLabel.
  }
  ?item wdt:P17 wd:Q20.
}
